name: "Feature Request"
description: "Request a new feature."
labels:
  - "type: feature"
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please enter a description."
      placeholder: "Short and explicit description of feature that needs to be added..."
  - type: "dropdown"
    id: area
    attributes:
      label: "Area"
      description: "Select what area this bug is related to."
      multiple: false
      options:
        - "User Interface"
        - "Machine Learning Model"
        - "Other"
