name: "Research Request"
description: "Request a research."
labels:
  - "type: research"
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please enter a description of your issue."
      placeholder: "Short and explicit description of your incident..."
  - type: "dropdown"
    id: area
    attributes:
      label: "Area"
      description: "Select what area it is related to."
      multiple: false
      options:
        - "User Interface"
        - "Machine Learning Model"
        - "Other"
